export const MESSAGE_FLAG = {
  AUTH: {
    REGISTER_USER: "REGISTER_USER",
    LOGIN_USER: "LOGIN_USER",
  },

  USER_PROFILE: {
    CREATE_CHARACTER: "CREATE_CHARACTER",
  },

  PLANER: {
    RAID: {
      CREATE_RAID_PLAN: "CREATE_RAID_PLAN",
      ENTER_RAID: "ENTER_RAID",
    },
  },
};
